addons:
  apt:
    packages:
    - libgmp-dev
language: ruby
cache: bundler
sudo: false
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
rvm:
  - ruby-head
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10
  - jruby-9.2.0.0
  - jruby-9.1.17.0

matrix:
  allow_failures:
    - rvm: ruby-head
